services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: alma-inventory-docker
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
    env_file:
      - .env
