<?php
/**
 * Historical Output Order Comparison & Regression Test Runner
 *
 * Compares the call number processing/sorting output of the new app against
 * historical CSV output files generated by the old app on apps.lib.purdue.edu.
 *
 * Run: php tests/compare_outputs.php
 */

require_once __DIR__ . '/../SortCallNumber.php';

$base_dir = __DIR__ . '/fixtures/cache_history';
$input_dir  = $base_dir . '/input';
$output_dir = $base_dir . '/output';
$report_file = $base_dir . '/report.md';

echo "=================================================================\n";
echo " Alma Inventory Output Order Regression Test Runner              \n";
echo "=================================================================\n\n";

if (!is_dir($output_dir)) {
    @mkdir($output_dir, 0775, true);
}

$csv_files = glob($output_dir . '/*.csv');

if (empty($csv_files)) {
    echo "⚠️  No historical output CSV files found in: $output_dir\n\n";
    echo "To sync historical files from apps.lib.purdue.edu, run:\n";
    echo "  ./scripts/sync_cache_history.sh\n\n";
    echo "Or place old CSV output files into:\n";
    echo "  $output_dir/\n";
    exit(0);
}

echo "Found " . count($csv_files) . " historical CSV output file(s) for analysis.\n\n";

$summary = [
    'total_files' => count($csv_files),
    'improved'    => 0,
    'same'        => 0,
    'worse'       => 0,
    'total_items' => 0,
    'old_ooo'     => 0,
    'new_ooo'     => 0,
    'details'     => []
];

foreach ($csv_files as $filepath) {
    $filename = basename($filepath);
    $handle = fopen($filepath, 'r');
    if (!$handle) continue;

    $header = fgetcsv($handle, 0, ',', '"', '\\'); // Correct_Position, Call_Number, norm_call_number, Title, Position Scanned, Problem, Barcode
    $items = [];
    $old_ooo_count = 0;

    while (($row = fgetcsv($handle, 0, ',', '"', '\\')) !== false) {
        if (count($row) < 3) continue;

        $correct_pos  = $row[0] ?? '';
        $call_number  = $row[1] ?? '';
        $norm_old     = $row[2] ?? '';
        $title        = $row[3] ?? '';
        $scanned_pos  = $row[4] ?? '';
        $problem_text = $row[5] ?? '';
        $barcode      = $row[6] ?? '';

        $is_old_ooo = (strpos($problem_text, 'OUT OF ORDER') !== false);
        if ($is_old_ooo) {
            $old_ooo_count++;
        }

        $items[] = [
            'correct_pos'  => $correct_pos,
            'call_number'  => $call_number,
            'norm_old'     => $norm_old,
            'title'        => $title,
            'scanned_pos'  => $scanned_pos,
            'problem_text' => $problem_text,
            'barcode'      => $barcode,
            'is_old_ooo'   => $is_old_ooo
        ];
    }
    fclose($handle);

    $item_count = count($items);
    if ($item_count === 0) continue;

    // Detect classification type (Dewey vs LC)
    $dewey_matches = 0;
    foreach ($items as $it) {
        if (preg_match('/^\d{3}/', trim($it['call_number']))) {
            $dewey_matches++;
        }
    }
    $is_dewey = ($dewey_matches / $item_count) > 0.5;

    // Re-index physical scanned order
    $scanned_items = $items;
    usort($scanned_items, function($a, $b) {
        return $a['scanned_pos'] <=> $b['scanned_pos'];
    });
    foreach ($scanned_items as $i => &$row) {
        $row['scan_loc'] = $i;
    }
    unset($row);

    // Build sortednk using new app sorting (SortDeweyObject / SortLCObject)
    $sortednk = $scanned_items;
    if ($is_dewey) {
        usort($sortednk, 'SortDeweyObject');
    } else {
        usort($sortednk, 'SortLCObject');
    }

    // Evaluate physical out-of-order count using process_barcodes.php neighbor check logic
    $new_ooo_count = 0;
    foreach ($sortednk as $key => $item) {
        $prev_scan_loc = ($sortednk[$key - 1]['scan_loc'] ?? -2) + 1;
        $scan_loc      = $sortednk[$key]['scan_loc'] + 1;
        $next_scan_loc = ($sortednk[$key + 1]['scan_loc'] ?? -2) + 1;

        $nextdiff = $next_scan_loc - $scan_loc;
        $prevdiff = $scan_loc - $prev_scan_loc;

        if ($prevdiff != 1 && $nextdiff != 1) {
            $new_ooo_count++;
        }
    }

    // Check exact sequence match percentage
    $exact_matches = 0;
    for ($i = 0; $i < $item_count; $i++) {
        if ($items[$i]['barcode'] === $sortednk[$i]['barcode']) {
            $exact_matches++;
        }
    }
    $match_pct = round(($exact_matches / $item_count) * 100, 1);

    // Status evaluation
    if ($new_ooo_count < $old_ooo_count) {
        $status = 'IMPROVED 🎉';
        $summary['improved']++;
    } elseif ($new_ooo_count === $old_ooo_count) {
        $status = 'SAME ✅';
        $summary['same']++;
    } else {
        $status = 'WORSE ❌';
        $summary['worse']++;
    }

    $summary['total_items'] += $item_count;
    $summary['old_ooo']     += $old_ooo_count;
    $summary['new_ooo']     += $new_ooo_count;

    $summary['details'][] = [
        'filename'      => $filename,
        'type'          => $is_dewey ? 'Dewey' : 'LC',
        'item_count'    => $item_count,
        'old_ooo'       => $old_ooo_count,
        'new_ooo'       => $new_ooo_count,
        'match_pct'     => $match_pct,
        'status'        => $status
    ];
}

// Render Terminal Table
printf("%-40s | %-6s | %-6s | %-7s | %-7s | %-7s | %-12s\n", "File", "Type", "Items", "Old OOO", "New OOO", "Match %", "Status");
echo str_repeat('-', 105) . "\n";

foreach ($summary['details'] as $d) {
    printf(
        "%-40s | %-6s | %6d | %7d | %7d | %6.1f%% | %-12s\n",
        strlen($d['filename']) > 40 ? substr($d['filename'], 0, 37) . '...' : $d['filename'],
        $d['type'],
        $d['item_count'],
        $d['old_ooo'],
        $d['new_ooo'],
        $d['match_pct'],
        $d['status']
    );
}

echo str_repeat('-', 105) . "\n";
echo "SUMMARY:\n";
echo "  Total Files Analyzed : " . $summary['total_files'] . "\n";
echo "  Total Items Scanned  : " . $summary['total_items'] . "\n";
echo "  Old Out-Of-Order Count: " . $summary['old_ooo'] . "\n";
echo "  New Out-Of-Order Count: " . $summary['new_ooo'] . "\n";
echo "  Improved Files 🎉   : " . $summary['improved'] . "\n";
echo "  Identical Files ✅   : " . $summary['same'] . "\n";
echo "  Worse Files (Regress): " . $summary['worse'] . "\n\n";

if ($summary['worse'] > 0) {
    echo "❌ REGRESSION DETECTED: New app produced more out-of-order items in {$summary['worse']} file(s).\n";
} else {
    echo "✅ SUCCESS: New app sorting order is IMPROVED or SAME across all analyzed files.\n";
}

// Generate markdown report
$md = "# Historical Call Number Sorting Comparison Report\n\n";
$md .= "Generated on: " . date('Y-m-d H:i:s') . "\n\n";
$md .= "## Summary Metrics\n\n";
$md .= "| Metric | Count |\n";
$md .= "| :--- | :--- |\n";
$md .= "| **Total Files Analyzed** | {$summary['total_files']} |\n";
$md .= "| **Total Items Scanned** | {$summary['total_items']} |\n";
$md .= "| **Old Out-of-Order Items** | {$summary['old_ooo']} |\n";
$md .= "| **New Out-of-Order Items** | {$summary['new_ooo']} |\n";
$md .= "| **Improved Files 🎉** | {$summary['improved']} |\n";
$md .= "| **Same Files ✅** | {$summary['same']} |\n";
$md .= "| **Worse Files ❌** | {$summary['worse']} |\n\n";

$md .= "## File Breakdown\n\n";
$md .= "| File | Type | Items | Old OOO | New OOO | Match % | Status |\n";
$md .= "| :--- | :--- | :---: | :---: | :---: | :---: | :--- |\n";

foreach ($summary['details'] as $d) {
    $md .= "| `{$d['filename']}` | {$d['type']} | {$d['item_count']} | {$d['old_ooo']} | {$d['new_ooo']} | {$d['match_pct']}% | {$d['status']} |\n";
}

file_put_contents($report_file, $md);
echo "Detailed report written to: $report_file\n";
